### ISSUE TITLE
api info

### ISSUE THREAD

**Issue by backdaniel** [timmc/midjourney-history-sync#1]
how did you found about these arguments on the api, and is there more? what is the logic? where can I see more info ...api/app/recent-jobs/?orderBy=new&jobStatus=completed&userId=${USER_ID}&dedupe=true&refreshApi=

**Comment by timmc** [comment]
I screwed around in the browser's network tab, found something that looked promising, and mucked about until it worked. :-P

(I didn't find any public documentation.)

**Comment by timmc** [comment]
(Also, apologies in advance, but I'm going to close the Issues feature for this repo -- I forgot it was enabled by default. I can't really provide support for this, and it's really Midjourney's job to make a supported export tool.)
